
SRC = miller-rabin.c
BIN = miller-rabin
LIB = -lm
FLAGS = -Wall -Wextra -Werror

miller-rabin:
	gcc $(FLAGS) $(SRC) $(LIB) -o $(BIN)

all: miller-rabin

clean:
	rm -f $(BIN)

fclean: clean

re: fclean all


